import { type NextPage } from "next";
import Head from "next/head";

import { api } from "../utils/api";
import React, { useState } from "react";
import { useRouter } from "next/router";

const SubmitBuild: NextPage = () => {
  const createBuildMutation = api.builds.submitBuild.useMutation();
  const [build, setBuild] = useState<string>("");
  const [matchUp, setMatchUp] = useState<string>("ZvT");
  const router = useRouter();

  const handleSubmitBuildOrder = async (e: React.FormEvent): Promise<void> => {
    e.preventDefault();

    try {
      await createBuildMutation.mutateAsync({
        matchUp,
        build,
      });
      void router.push("/builds");
    } catch (error) {
      console.error(error);
    }
  };

  return (
    <>
      <Head>
        <title>Submit a Build Order</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center gap-4 bg-gradient-to-b from-[#2e026d] to-[#15162c] text-white">
        <h1>Submit a Build order</h1>
        <form className="flex flex-col gap-4" onSubmit={handleSubmitBuildOrder}>
          <label htmlFor="match-up-select">Match up</label>
          <select
            id="match-up-select"
            className="text-black"
            required
            value={matchUp}
            onSelect={(e) => setMatchUp(e.target.value)}
          >
            <option value="zvt">ZvT</option>
            <option value="zvp">ZvP</option>
            <option value="zvz">ZvZ</option>

            <option value="pvt">PvT</option>
            <option value="pvp">PvP</option>
            <option value="pvz">PvZ</option>

            <option value="tvt">TvT</option>
            <option value="tvp">TvP</option>
            <option value="tvz">TvZ</option>
          </select>
          <textarea
            required
            className="p-3 text-black"
            value={build}
            onChange={(e) => setBuild(e.target.value)}
          />
          <button className="rounded-sm bg-white p-2 text-black">submit</button>
        </form>
      </main>
    </>
  );
};

export default SubmitBuild;
